# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('desc', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('unit', models.CharField(max_length=30, verbose_name='\u5355\u4f4d')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/goods', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('detail', models.CharField(default='\u5546\u54c1\u8be6\u60c5', max_length=1000, verbose_name='\u5546\u54c1\u8be6\u60c5')),
                ('isdelete', models.BooleanField(default=False, verbose_name='\u5220\u9664')),
            ],
        ),
    ]
