# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200, verbose_name='bookname')),
                ('bookstarttime', models.CharField(max_length=30, verbose_name='bookstarttime')),
                ('bookinfo', models.CharField(max_length=200, verbose_name='bookinfo')),
                ('booktype', models.CharField(max_length=30, verbose_name='booktype')),
                ('bookendtime', models.CharField(max_length=30, verbose_name='bookendtime')),
                ('bookremark', models.CharField(max_length=1000, verbose_name='bookremark')),
            ],
        ),
    ]
